version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.${ENV}
    container_name: "c_image_api"
    environment:
      TOKEN: ${IMAGE_API_TOKEN}
      UUID_SEED: ${UUID_SEED}
    working_dir: /src
    volumes:
      - ./image_api:/src
      - node_modules:/src/node_modules:cached
    ports:
      - 3020:3000
    entrypoint: >
      node
      ./bin/www
    logging:
      options:
        max-size: '10m'
        max-file: '15'
      driver: json-file
